version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootwpnexus2021
       MYSQL_DATABASE: wpnexus
       MYSQL_USER: wpnexus
       MYSQL_PASSWORD: wpnexus2021

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9010:80"
     restart: always
     volumes:
         - ./wp-nexus:/var/www/html/wp-content/plugins/wp-nexus:ro
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wpnexus
       WORDPRESS_DB_PASSWORD: wpnexus2021
       WORDPRESS_DB_NAME: wpnexus

volumes:
    db_data: {}
